# Generated by Django 4.2.7 on 2025-10-15 11:41

from django.db import migrations, models
import habits.validators


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.PositiveSmallIntegerField(validators=[habits.validators.validate_execution_time], verbose_name='время выполнения в секундах'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ежедневно'), (7, 'Еженедельно')], default=1, validators=[habits.validators.validate_frequency], verbose_name='периодичность'),
        ),
    ]
